[variables]
NPM_CONFIG_AUDIT = false
NPM_CONFIG_FUND = false
NODE_ENV = production

[phases.install]
cmd = "npm install --omit=dev --no-package-lock"

[phases.build]
cmd = "echo 'Build phase completed'"

[start]
cmd = "npm start"
